Repository codeandkey/boom, pull requests merged in 2019-08, with the labels that each got.

#66 Implement camera auto scaling
  src/camera.lua
  src/main.lua
Labels: Feature, Visual

#69 Set sprites in object_type.lua
  src/component_types/character.lua
  src/object_types/npc.lua
  src/object_types/player.lua
Labels: Feature, Visual

#68 Add minor, greater imp sprites
  src/assets/sprites/32x32_greater_imp.png
  src/assets/sprites/32x32_minor_imp.png
Labels: Visual

#61 Add The Hero sprites
  src/assets/sprites/32x32_hero-jump.png
  src/assets/sprites/32x32_hero-walk.png
  src/assets/sprites/32x32_hero.png
  src/assets/sprites/32x32_hero_run.png
Labels: Story, Visual

#70 Fix hero walk anim naming
  src/assets/sprites/32x32_hero-run.png
  src/object_types/npc.lua
  src/object_types/player.lua
Labels: Visual, bug

#72 Updates to NPC/Player animations
  src/assets/sprites/32x32_hero.png
  src/object_types/npc.lua
  src/object_types/player.lua
Labels: Visual, bugfix

#73 Main menu, persistent data, and string databases
  .gitignore
  src/assets/fonts/pixeled.ttf
  src/assets/maps/main_menu.lua
  src/assets/maps/main_menu.tmx
  src/camera.lua
  src/event.lua
  src/fs.lua
  src/input.lua
  src/main.lua
  src/object_types/main_menu.lua
  src/opts.lua
  src/strings.lua
  src/strings/english.lua
Labels: Feature, GUI

#75 Add smooth, safer map transitions
  src/map.lua
  src/object_types/main_menu.lua
Labels: Feature, Visual

#77 Add background property to tile layers
  src/map.lua
  src/tile_layer.lua
Labels: Visual

#79 Add player interaction, load triggers
  src/assets/maps/4096x4096_stone_castle.tsx
  src/assets/maps/first_zone.lua
  src/assets/maps/first_zone.tmx
  src/assets/maps/intro.lua
  src/assets/maps/intro.tmx
  src/assets/sprites/4096x4096_stone_castle.png
  src/component_types/character.lua
  src/input.lua
  src/map.lua
  src/object.lua
  src/object_types/load_trigger.lua
  src/object_types/main_menu.lua
  src/object_types/player.lua
Labels: Mechanic

#57 Add early introductory maps, castle tileset
  src/assets/maps/first_zone.lua
  src/assets/maps/first_zone.tmx
  src/assets/maps/intro.lua
  src/assets/maps/intro.tmx
  src/assets/sprites/4096x4096_stone_castle.png
Labels: Mechanic, Story, Visual, World

#81 Camera panic movement
  src/camera.lua
  src/object_types/player.lua
Labels: bugfix

#84 Implement autosaving / continue game
  src/map.lua
  src/object_types/main_menu.lua
  src/object_types/player.lua
  src/opts.lua
  src/strings/english.lua
Labels: Feature

#74 Add destructible crate object
  src/assets/maps/test.lua
  src/assets/maps/test.tmx
  src/assets/sprites/28x4_crate_board.png
  src/assets/sprites/32x32_crate.png
  src/assets/sprites/32x4_crate_frame.png
  src/object_types/crate.lua
  src/object_types/explosion.lua
  src/object_types/gib.lua
Labels: Feature, Mechanic

#85 Add foreground fade trigger type
  src/map.lua
  src/object_types/secret_trigger.lua
Labels: Feature, Visual

#87 Player movement adjustments
  src/component_types/character.lua
Labels: Mechanic, bugfix

#90 Implement player death sequence, time control, post-processing pipeline
  src/camera.lua
  src/component_types/character.lua
  src/main.lua
  src/map.lua
  src/object.lua
  src/object_types/explosion.lua
  src/object_types/gib.lua
  src/object_types/player.lua
  src/post.lua
  src/shaders.lua
Labels: Feature, Mechanic, Visual
