Repository codeandkey/boom, pull requests merged in 2019-07, with the labels that each got.

#41 Smooth horizontal and upwards collisions for player, npc
  src/objects/npc.lua
  src/objects/player.lua
Labels: bug

#48 Add gibs, NPC and player deaths
  src/assets/sprites/12x9_player_head.png
  src/assets/sprites/14x13_player_body.png
  src/assets/sprites/19x13_player_body.png
  src/assets/sprites/5x9_player_leg.png
  src/assets/sprites/6x13_player_arm.png
  src/map.lua
  src/obj.lua
  src/objects/explosion.lua
  src/objects/gib.lua
  src/objects/npc.lua
  src/objects/physbox.lua
  src/objects/player.lua
  src/physics_groups.lua
  src/sprite.lua
Labels: Feature, Mechanic, Visual

#53 Fix crash on enemy death
  src/objects/enemy_bomber.lua
Labels: Mechanic, bug

#52 Animations for running/jumping
  src/assets/sprites/32x32_player-jump.png
  src/assets/sprites/32x32_player-walk.png
  src/objects/enemy_bomber.lua
  src/objects/npc.lua
  src/objects/player.lua
  src/sprite.lua
Labels: Visual

#64 Mechanics Update
  src/assets/sprites/32x32_hero_run.png
  src/component_types/character.lua
Labels: Feature, Mechanic

#67 Add player idle animation
  src/assets/sprites/32x32_player.png
  src/component_types/character.lua
Labels: Visual
