Repository codeandkey/boom, pull requests merged in 2019-06, with the labels that each got.

#12 Add grenade throwing
  src/assets/sprites/32x32_player.png
  src/map.lua
  src/obj.lua
  src/objects/explosion.lua
  src/objects/nade.lua
  src/objects/player.lua
Labels: Feature, Mechanic

#13 Add CI linting and style checking
  .luacheckrc
  .travis.yml
  CONTRIBUTING.md
  src/camera.lua
  src/main.lua
  src/map.lua
  src/obj.lua
  src/objects/explosion.lua
  src/objects/nade.lua
  src/objects/physbox.lua
  src/objects/player.lua
Labels: Feature, Linting

#15 Make noclip interact with physics
  src/objects/noclip.lua
Labels: Feature, World

#17 Throw aiming / physics grenades
  src/objects/explosion.lua
  src/objects/nade.lua
  src/objects/player.lua
Labels: Feature, Mechanic

#21 Grenade flashing effect
  src/objects/nade.lua
  src/shaders.lua
Labels: Visual

#16 Explosion physics
  .luacheckrc
  src/assets/maps/test.lua
  src/assets/maps/test.tmx
  src/objects/explosion.lua
Labels: Feature, Mechanic

#24 Add slowdown when player is in the air
  src/objects/player.lua
Labels: Feature, Mechanic

#25 Add object types to map section of readme
  README.md
Labels: Doc

#22 Add more polished player sprite, hood character sprite, and large player sprite
  src/assets/sprites/32x32_hood.png
  src/assets/sprites/32x32_player.png
  src/assets/sprites/64x64_player.png
Labels: Visual

#26 Use nearest texture filtering
  src/main.lua
Labels: Visual

#18 Implement game camera
  src/camera.lua
  src/main.lua
  src/objects/camera.lua
  src/objects/player.lua
Labels: Feature, Mechanic

#29 Sprite rendering improvements
  src/objects/player.lua
  src/sprite.lua
Labels: Visual

#27 Add player walk animation
  src/assets/sprites/32x32_player-walk.png
  src/assets/sprites/32x32_player.png
  src/assets/sprites/64x64_player.png
  src/objects/camera.lua
  src/objects/player.lua
  src/sprite.lua
Labels: Visual

#37 Persistent options
  src/assets/options.lua
  src/main.lua
  src/options.lua
Labels: Feature

#38 Add Non-Player Character (NPC)
  src/assets/maps/test.lua
  src/assets/maps/test.tmx
  src/objects/npc.lua
Labels: Feature, World

#39 Fix player vibrating above ground
  src/objects/npc.lua
  src/objects/player.lua
  src/util.lua
Labels: bug

#43 Add camera shake effect for explosions
  src/camera.lua
  src/objects/explosion.lua
Labels: Visual

#42 Align noclip objects in map
  src/assets/maps/test.lua
  src/assets/maps/test.tmx
Labels: World

#40 Use time-based throw timers
  src/objects/player.lua
Labels: bug

#46 Smooth camera vertical motion
  src/objects/camera.lua
Labels: bug

#45 Brighten background
  src/main.lua
Labels: Visual
