Repository codeandkey/boom, pull requests merged in 2020-06, with the labels that each got.

#126 Grenade Rework / Central Mechanic
  src/assets/maps/first_zone.lua
  src/assets/maps/first_zone.tmx
  src/assets/sprites/16x16_qmark.png
  src/component_types/character.lua
  src/input.lua
  src/object_types/explosion.lua
  src/object_types/main_menu.lua
  src/object_types/nade.lua
  src/object_types/npc.lua
  src/object_types/player.lua
Labels: Feature, Mechanic, priority

#132 Add walljump mechanic
  src/assets/sprites/char/player/jump-loop.png
  src/assets/sprites/char/player/jump-start.png
  src/assets/sprites/char/player/wallslide.png
  src/component_types/character.lua
Labels: Mechanic

#133 Fix object interaction, remove old dialog sequences
  src/object_types/dialog_sequence.lua
  src/object_types/player.lua
Labels: bugfix

#134 Add dialog, HUD subsystems
  src/assets/maps/first_zone.lua
  src/assets/maps/intro.lua
  src/assets/maps/main_menu.lua
  src/assets/maps/sky.lua
  src/assets/maps/test.lua
  src/assets/maps/town.lua
  src/assets/maps/vale.lua
  src/assets/sequences/merchant1.lua
  src/assets/sequences/merchant2.lua
  src/assets/sequences/merchant3.lua
  src/assets/sequences/merchant_int1.lua
  src/assets/sequences/merchant_int2.lua
  src/assets/sequences/oldman1.lua
  src/assets/sequences/oldman2.lua
  src/assets/sequences/oldman_int1.lua
  src/assets/sequences/oldman_int2.lua
  src/camera.lua
  src/component_types/character.lua
  src/dialog.lua
  src/fs.lua
  src/hud.lua
  src/main.lua
  src/object_types/load_trigger.lua
  src/object_types/npc.lua
  src/object_types/player.lua
  src/sequences/test_sequence.lua
Labels: Feature, GUI

#135 Add placeholder grenade explosion effects
  src/object_types/effect_explosion.lua
  src/object_types/explosion.lua
  src/util.lua
Labels: Visual
