Repository codeandkey/boom, pull requests merged in 2020-05, with the labels that each got.

#116 Interact prompt
  src/assets/maps/first_zone.lua
  src/assets/maps/first_zone.tmx
  src/assets/maps/intro.lua
  src/assets/maps/intro.tmx
  src/assets/sprites/16x16_blank-key.png
  src/assets/sprites/32x32_blank-key.png
  src/object_types/load_trigger.lua
  src/object_types/player.lua
Labels: Feature, GUI

#120 Add squish effect to characters
  src/component_types/character.lua
  src/sprite.lua
Labels: Feature, Visual

#108 Implement dialog sequences and cutscenes
  src/object_types/dialog_sequence.lua
  src/object_types/player.lua
  src/sequences/test_sequence.lua
Labels: Feature, dont-merge-yet, priority

#127 Updated README
  README.md
Labels: Doc

#128 Fix explosions not working
  src/object_types/explosion.lua
Labels: Mechanic, bugfix
